### PR TITLE
WIP: First step

### LINKED ISSUE #39: Dynamic admin page
For example
```php
function add_sweep_admin( $group, $slug, $title, $count, $total ) {
            <tr>
                <td>
                    <strong><?php _e( $title, 'wp-sweep' ); ?></strong>
                    <p class="sweep-details" style="display: none;"></p>
                </td>
                <td>
                    <span class="sweep-count"><?php echo esc_html( number_format_i18n( $count ) ); ?></span>
                </td>
                <td>
                    <span class="sweep-percentage"><?php echo esc_html( WPSweep::get_instance()->format_percentage( $count, $total ) ); ?></span>
                </td>
                <td>
                    <?php if ( empty( $count ) ) : ?>
                        <?php _e( 'N/A', 'wp-sweep' ); ?>
                    <?php else : ?>
                        <button data-action="sweep" data-sweep_name="<?php echo $slug; ?>"
                            data-sweep_type="posts" data-nonce="<?php echo esc_attr( wp_create_nonce( 'wp_sweep_' . $slug ) ); ?>"
                            class="button button-primary btn-sweep"><?php _e( 'Sweep', 'wp-sweep' ); ?></button>
                        <button data-action="sweep_details" data-sweep_name="<?php echo $slug; ?>"
                            data-sweep_type="posts" data-nonce="<?php echo wp_create_nonce( 'wp_sweep_details_' . $slug ); ?>"
                            class="button btn-sweep-details"><?php _e( 'Details', 'wp-sweep' ); ?></button>
                    <?php endif; ?>
                </td>
            </tr>
}

add_sweep_admin( 'post', 'revisions', 'Revisions', $revisions, $total_posts );
```

### PR DESCRIPTION
**Pull request by szepeviktor**
What need to be done

- adding all sweep types
- adding all sweeps
- rework REST API class
- adding missing PHPDoc-s

Closes #39

### CODE REVIEW

**Comment by szepeviktor** [comment]
@lesterchan I was dreaming back then!

Have you seen the results of the recent research?
https://github.com/szepeviktor/small-project/blob/master/MAIN-FILE-PARTS.md includes sample source code.

**Comment by lesterchan** [comment]
Wow this is good! But since it is WIP, do you want it to merged to another branch instead of master?

**Comment by szepeviktor** [comment]
We need somebody to finish this....

**Comment by lesterchan** [comment]
lol yea i guess eventually :D, not dapping much into WP much.

**Comment by szepeviktor** [comment]
Old times ...
I was dreaming about becoming a developer for WordPress.

**Pull request closed without merging**
