### PR TITLE
added WP CLI command for wp-sweep

### PR DESCRIPTION
**Pull request by Nikschavan**
First pass at #17, suggestions welcome :)

### CODE REVIEW

**Comment by lesterchan** [comment]
Thank you so much for this!

**Comment by Nikschavan** [comment]
@lesterchan any plans when this will be released on WordPress repo?

**Comment by lesterchan** [comment]
I normally update my plugins with the next release of WP, in this case will be 4.6 =)

**Comment by collinbarrett** [comment]
If I now run `wp sweep --all` on a cron, is their no need to run `wp db optimize` anymore? Is the database optimize that wp-sweep performs the same as the one built into wp-cli?

Thanks.

**Comment by lesterchan** [comment]
@collinbarrett yes, wp sweep -- includes optimize.

**Comment by collinbarrett** [comment]
@lesterchan perfect. can't wait for the wp-cli support to be rolled out through the .org plugin repo!

**Comment by collinbarrett** [comment]
I just manually installed the latest code (couldn't wait for the release). wp-cli integration seems to work like a charm. Thanks so much!

**Comment by jscmal** [comment]
Hi, @Nikschavan,  I would require a Feature. 

`wp sweep --all` doesn't consider the DB of a multisite. 

Kindly may you add the feature to use it also for a multisite that has several websites with just 1 DataBase, then with some core tables in common and other tables that are repeated for each site?

I have 1 multisite with 2 sites the DB has different table prefixes for the 2 sites.

Please, may you do this?

Here my Feature Request that I wrote on the Support Page of the Plugin: https://wordpress.org/support/topic/wp-cli-on-a-multisite-with-1-data-base-and-2-different-table-prefixex/#post-10393725

Kind regards

G. Aloe

**Comment by Nikschavan** [comment]
Hi @jscmal, There's a trick to run all the WP-CLI commands on MS -
`wp site list --field=url | xargs -n1 -I % wp --url=%  sweep --all`

@danielbachhuber has a blog post which explains this nicely - https://danielbachhuber.com/tip/run-wp-cli-command-wordpress-multisite/

**Comment by jscmal** [comment]
Thank you @Nikschavan. :)
It works concretely well. I have to say that I had never used xargs before.

Now I have my script in cron that clean everything after the midnight backup.

**Pull request merged**
