### PR TITLE
Move main class to a separate file

### PR DESCRIPTION
**Pull request by szepeviktor**
@lesterchan 👋🏻

kép

### CODE REVIEW

**Comment by lesterchan** [comment]
@szepeviktor this breaks admin.php

**Comment by szepeviktor** [comment]
I'm sorry.
What is the error?

**Comment by szepeviktor** [comment]
I see. The REST class instantiates `new WPSweep()`

**Comment by szepeviktor** [comment]
Should I replace those `new`-s with `WPSweep::get_instance()`?

**Comment by lesterchan** [comment]
https://wordpress.org/support/topic/fatal-error-in-the-wp-sweep-version-1-1-6/

I make the arguments optional and it works =)

**Comment by lesterchan** [comment]
Not sure is there a better way of not passing in __FILE__ to the class.

**Comment by szepeviktor** [comment]
I think `WPSweep` should be instantiated (`new WPSweep()`) only once in the `get_instance` method.

**Comment by szepeviktor** [comment]
Multiple instantiations case really bad side-effects. For example multiple hooking.

**Comment by szepeviktor** [comment]
> Not sure is there a better way of not passing in **FILE** to the class.

Please do not tell anyone. I will deny it.

Put `__FILE__` into a global constant.

**Comment by lesterchan** [comment]
@szepeviktor LOL I let you figure it out and send a PR to change to `new WPSweep()` But the reason I use a singleton is that I need to access the functions outside.

**Pull request merged**
